import { test, expect } from '@playwright/test';
test('basic test', async({ page })=>{
    await (page.goto('https://demoqa.com/'))
    await expect(page).toHaveURL('https://demoqa.com')
    await page.getByRole('heading',{name: 'Elements'}).click()
    await page.getByText('Web Tables').click()
    await page.getByRole('button', { name: 'Add' }).click()
    await page.getByPlaceholder('First Name').fill('Alden')
    expect('Alden').toBeTruthy()
    await page.getByPlaceholder('Last Name').fill('Cantrell')
    expect('Cantrell').toBeTruthy()
    await page.getByPlaceholder('name@example.com').fill('test@test.com')
    expect('test@test.com').toBeTruthy()
    await page.getByPlaceholder('Age').fill('30')
    expect('30').toBeTruthy()
    await page.getByPlaceholder('Salary').fill('12345')
    expect('12345').toBeTruthy()
    await page.getByPlaceholder('Department').fill('QA')
    expect('QA').toBeTruthy()
    await page.getByRole('button', { name: 'Submit' }).click()
    expect('Submit').toBeFalsy()
})